name: 0xf ➼ Debug (gh-runner) Ubuntu-22.04
#Image: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
on:
  workflow_dispatch:
env:
  #Authenticate with Ephemeral Key: https://login.tailscale.com/admin/settings/keys
  TSKEY: "tskey-auth-kfVcBA5CNTRL-9ij5f3MZEa6yJGrbtEHma6FFY9jsXgqN"
  THOST: "gh-runner-ubuntu"
  TUSER: "runner"
  
jobs:
  build:
    runs-on: ubuntu-latest
    #Default Timeout= 6 Hr (360 Mins) : https://nesin.io/blog/github-action-timeout
    #Docs: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
    timeout-minutes: 690000 
    permissions:
      contents: write
      
    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
          
      - name: Setup Tailscale
        run: |
          #Download & Chmod
          sudo curl -qfSL "https://raw.githubusercontent.com/Azathothas/Static-Binaries/main/tailscale/tailscale_amd_x86_64_Linux" -o "/usr/local/bin/tailscale"
          sudo curl -qfSL "https://raw.githubusercontent.com/Azathothas/Static-Binaries/main/tailscale/tailscaled_amd_x86_64_Linux" -o "/usr/local/bin/tailscaled"
          sudo chmod +xwr /usr/local/bin/tailscale*
          #Enable Userspace Networking
          sudo tailscaled --tun=userspace-networking --socks5-server=localhost:9025 --outbound-http-proxy-listen=localhost:9025 >/dev/null 2>&1 &
          #Authenticate with Ephemeral Key: https://login.tailscale.com/admin/settings/keys
          sudo tailscale up --ssh --hostname="${{ env.THOST }}" --authkey="${{ env.TSKEY }}" 
          #Check Status
          sudo tailscale status --peers=false
          #Get SSH String
          SSH_IP=$(sudo tailscale ip -4 | tr -d '\n')
          ssh_connection_string="SSH: ssh $USER@$SSH_IP"
          echo -e "$ssh_connection_string"
          sleep 60s
          #Also shows up on: https://login.tailscale.com/admin/machines
      
      - name: Install CoreUtils
        #if: env.versions_same != 'true'
        run: |
           sudo apt-get update -y
           sudo apt-get --fix-missing
           sudo apt-get install -y bison build-essential ca-certificates ccache flex '*glibc*' jq 'libssl*' lzip musl musl-dev musl-tools 'openssl*' p7zip-full pkg-config qemu-user-static wget
        continue-on-error: true

      - name: Install Build Dependencies
        run: "\
          sudo apt-get update\n
          sudo apt-get install -y --no-install-recommends \
          g++-aarch64-linux-gnu \
          g++-arm-linux-gnueabi \
          g++-arm-linux-gnueabihf \
          g++-i686-linux-gnu \
          g++-m68k-linux-gnu \
          g++-mips-linux-gnu \
          g++-mipsel-linux-gnu \
          g++-mips64-linux-gnuabi64 \
          g++-mips64el-linux-gnuabi64 \
          g++-powerpc-linux-gnu \
          g++-powerpc64-linux-gnu \
          g++-powerpc64le-linux-gnu \
          g++-riscv64-linux-gnu \
          g++-s390x-linux-gnu \
          g++-sh4-linux-gnu libc6-dev-sh4-cross\n"
        continue-on-error: true
        
      - name: Install Addons
        run: |
           # for rust & cargo
           cargo install -f cross  
           # for binaries
           curl -qfsSL "https://zyedidia.github.io/eget.sh" | bash
           sudo mv ./eget* "/usr/local/bin/eget"
           sudo chmod +xwr "/usr/local/bin/eget"
           # croc
           sudo curl -qfSL "https://raw.githubusercontent.com/Azathothas/Static-Binaries/main/croc/croc_amd_x86_64_Linux" -o "/usr/local/bin/croc"
           sudo chmod +xwr "/usr/local/bin/croc"
        continue-on-error: true

      - name: Install upX
        if: env.versions_same != 'true'
        run: |
          cd $(mktemp -d) && curl -qfLJO "$(curl -s https://api.github.com/repos/upx/upx/releases/latest | jq -r '.assets[].browser_download_url' | grep -i 'amd64_linux')"
          find . -type f -name '*tar*' -exec tar -xvf {} \;
          sudo find . -type f -name 'upx' -exec mv {} "$(which upx)" \;  
        continue-on-error: true
        
      - name: Install Zig
        run: |
         cd $(mktemp -d) && 
         curl -qfSLJO $(curl -qfsSL "https://ziglang.org/download/index.json" | jq -r '.master | ."x86_64-linux".tarball')
         find . -type f -name '*.tar*' -exec tar -xvf {} \;
         sudo mkdir -p "/usr/local/zig" && sudo mv "$(find . -maxdepth 1 -type d | grep -v '^.$')"/* "/usr/local/zig" 
         export PATH="/usr/local/zig:/usr/local/zig/lib:/usr/local/zig/lib/include:$PATH"
        continue-on-error: true
        
      - name: Run Custom Cmd
        run: |
           echo "Hellow"
        continue-on-error: true
        
      - name: Breakpoint || Sleep ∞
        run: |        
          while :; do sleep 1; done  
